baseURL: "https://www.example.com/"
theme: "move-up"
languageCode: "en-us"

title: "Up Business"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Up Business"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "3891 Ranchview Dr. Richardson, California 62639"
    - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "contact@thetalent.pro"
    - "207.555.0119"

  copyright: "© 2022 Up Business All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Our story"
      url: "/#our-story"
      weight: 2

    - name: "What we offer"
      url: "/#what-we-offer"
      weight: 3

    - name: "Blog"
      url: "/blog"
      weight: 4

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    
    - name: "Our story"
      url: "/#our-story"
      weight: 2

    - name: "What we offer"
      url: "/#what-we-offer"
      weight: 3


    - name: "Blog"
      url: "/blog"
      weight: 4

taxonomies:
  series: "series"
  tags: "tags"
