
# Start proxy: npx netlify-cms-proxy-server
# when using a custom proxy server port
local_backend:
  url: http://localhost:8081/api/v1
  allowed_hosts: ['192.168.0.1']

backend:
  name: git-gateway
  branch: main
  
site_url: https://business.anphabe.com

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files

  # Required - a list of locales to show in the editor UI
  locales: [en, vi]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: vi

slug:
  encoding: "ascii"
  clean_accents: true

collections: # A list of collections the CMS should be able to edit
  - name: 'post' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Post' # Used in the UI
    label_singular: 'Post' # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: 'content/post'
    slug: '{{slug}}-{{year}}{{month}}{{day}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    sortable_fields: ['date', 'title']
    create: true # Allow users to create new documents in this collection
    i18n: true
    view_filters:
      - label: Posts With Index
        field: title
        pattern: 'This is post #'
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1', i18n: true }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, i18n: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD',
          i18n: true
        }
      - label: 'Image intro'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''
        i18n: true
        hint: 'Size: 348x227px'

      - {label: "Link to", name: "field_url", widget: "string", required: false, hint: "Link to other page. Ex: https://anphabe.com", i18n: true}
      - { label: 'Body', name: 'body', widget: 'markdown', required: false,  hint: 'How to use Markdown: https://business.anphabe.com/guide/markdown', i18n: true }

  